### ISSUE TITLE
過去のログデータを返す REST API を追加する

### ISSUE THREAD

**Issue by dynamis** [webdino/enocean-console-demo-server#1]
クライアントが起動時にサーバに過去データを問い合わせてそれを表示するところから始められるように。また、測定をした後でそれをサンプルデータとしてクライアント側で保存してデモモードで利用できるようにしたい。

**Comment by epli2** [comment]
実装した！

https://github.com/webdino/enocean-console-demo-server/commit/cefc9528514a11f0672e306e2ca4021bcf863584
https://github.com/webdino/enocean-console-demo-server/commit/87866cb1e044fef9806475f8f5cb332b104e977f
